//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya_DuzhikIlya
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryResult
    {
        public int ResultID { get; set; }
        public Nullable<int> InventoryID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public int ActualQuantity { get; set; }
        public Nullable<int> WarehouseID { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Product Product { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
